### ISSUE TITLE
Программа виснет после последних обновлений

### ISSUE THREAD

**Issue by finast** [SBProX/SBProX-Dev#781]
Программа виснет после последних обновлений. Особенно невозможно стало работать в симуляторе.

**Comment by SeregaTS22** [comment]
присоединяюсь

**Comment by SBProX** [comment]
В последних обновлениях исправлялись ошибки только в инструментах рисования и дин. профилях. Маловероятно что это могло что-то поменять.
Под виснет что вы подразумеваете?

**Comment by danilp2** [comment]
Присоединяюсь. У меня стала тормозить на графиках, с большим периодом (период 4 года, недельки) - не любые действия реагирует с большой задержкой.

**Comment by SBProX** [comment]
@danilp2 Можете сообщить ваш логин и имя workspace, посмотрим как работает на вашем примере.

**Comment by danilp2** [comment]
> 
> 
> @danilp2 Можете сообщить ваш логин и имя workspace, посмотрим как работает на вашем примере.

danilp2@yandex.ru
WDH
На более мощном компе практически не тормозит

**Comment by SBProX** [comment]
@danilp2 Да, действительно работает плохо.
Вынесем завтра задачу по оптимизации графика на первое место, и будем работать над этим.

**Comment by SBProX** [comment]
@danilp2 @finast 

Выложили обновление где оптимизирована работа с графиком насколько это было возможно.

@danilp2 - на вашем workspace стоят большие периоды данных, на волатильных инструментах по типу Si. Вы должны понимать что быстро это работать не будет, так как маленький шаг цены у вас. Ставьте шаг цены 10 или 20 на таком инструменте, тогда будет работать нормально.

Тормоза появляются из-за того, что вы ставите профили - представьте сколько элементов нужно отрисовать платформе с шагом цены 1 по Si, за три года истории!

Мы ставили такой же график в volfix с volume profile - там тормоза такие что вообще работать нельзя. В Tiger лучше, но все равно тормозит.

Обращайтесь.

**Comment by danilp2** [comment]
Спасибо большое. Учту Данил 05.11.2019, 18:57, "SBPro X" <notifications@github.com>:@danilp2 @finastВыложили обновление где оптимизирована работа с графиком насколько это было возможно.@danilp2 - на вашем workspace стоят большие периоды данных, на волатильных инструментах по типу Si. Вы должны понимать что быстро это работать не будет, так как маленький шаг цены у вас. Ставьте шаг цены 10 или 20 на таком инструменте, тогда будет работать нормально.Тормоза появляются из-за того, что вы ставите профили - представьте сколько элементов нужно отрисовать платформе с шагом цены 1 по Si, за три года истории!Мы ставили такой же график в volfix с volume profile - там тормоза такие что вообще работать нельзя. В Tiger лучше, но все равно тормозит.Обращайтесь.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
